name: Kaia_5m_Reload
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node update.js
      - name: Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add realtime.json
          git commit -m "Update Kaia Data" || exit 0
          git push
